version: "3.3"
services:
   zookeeper:
      image: "zookeeper"
      ports:
      - "2181:2181"
   my-app:
      image: "test"
      deploy:
         replicas: 2
      depends_on:
      - zookeeper

